[package]
name = "patch-test-prover-bigint"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[dependencies]
common = { path = "../../../common" }